// Mirrors backend/src/modules/game-gateway/ws-events.constants.ts
// Keep these two files in sync manually (or extract to a shared package
// later if the monorepo grows).

export const WS_EVENTS_IN = {
  JOIN_ROOM: 'join_room',
  LEAVE_ROOM: 'leave_room',
  PLAYER_READY: 'player_ready',
  START_GAME: 'start_game',
  PAUSE_GAME: 'pause_game',
  RESUME_GAME: 'resume_game',
  ROLL_DICE: 'roll_dice',
  MAKE_MOVE: 'make_move',
  KICK_PLAYER: 'kick_player',
  DELETE_ROOM: 'delete_room',
  JOIN_QUEUE: 'join_queue',
  CANCEL_QUEUE: 'cancel_queue',
  OLO_LIVE_POSITIONS: 'olo_live_positions',
  OLO_SHOT_RESULT: 'olo_shot_result',
  MONOPOLY_PURCHASE_DECISION: 'monopoly_purchase_decision',
  MONOPOLY_BUILD_HOUSE: 'monopoly_build_house',
  MONOPOLY_PAY_JAIL_FINE: 'monopoly_pay_jail_fine',
  MONOPOLY_PLACE_BID: 'monopoly_place_bid',
  MONOPOLY_PASS_AUCTION: 'monopoly_pass_auction',
  MONOPOLY_PROPOSE_TRADE: 'monopoly_propose_trade',
  MONOPOLY_RESPOND_TRADE: 'monopoly_respond_trade',
  MONOPOLY_MORTGAGE: 'monopoly_mortgage',
  MONOPOLY_UNMORTGAGE: 'monopoly_unmortgage',
  MONOPOLY_SELL_HOUSE: 'monopoly_sell_house',
  MONOPOLY_PAY_DEBT: 'monopoly_pay_debt',
  MONOPOLY_DECLARE_BANKRUPTCY: 'monopoly_declare_bankruptcy',
  CONQUEST_REINFORCE: 'conquest_reinforce',
  CONQUEST_MOVE_ARMIES: 'conquest_move_armies',
  CONQUEST_ATTACK: 'conquest_attack',
  CONQUEST_END_ATTACK_PHASE: 'conquest_end_attack_phase',
  CONQUEST_END_TURN: 'conquest_end_turn',
  CONQUEST_TRADE_CARDS: 'conquest_trade_cards',
  CONQUEST_PASS_TURN: 'conquest_pass_turn',
} as const;

export const WS_EVENTS_OUT = {
  ROOM_STATE: 'room_state',
  ROOM_LIST_UPDATED: 'room_list_updated',
  PLAYER_JOINED: 'player_joined',
  PLAYER_LEFT: 'player_left',
  PLAYER_KICKED: 'player_kicked',
  ROOM_DELETED: 'room_deleted',
  PLAYER_DISCONNECTED: 'player_disconnected',
  PLAYER_RECONNECTED: 'player_reconnected',
  GAME_STARTED: 'game_started',
  GAME_PAUSED: 'game_paused',
  GAME_RESUMED: 'game_resumed',
  DICE_ROLLED: 'dice_rolled',
  AWAITING_MOVE_CHOICE: 'awaiting_move_choice',
  MOVE_APPLIED: 'move_applied',
  TURN_SKIPPED: 'turn_skipped',
  GAME_OVER: 'game_over',
  QUEUE_JOINED: 'queue_joined',
  QUEUE_CANCELLED: 'queue_cancelled',
  MATCH_FOUND: 'match_found',
  ERROR: 'error_event',
  OLO_LIVE_POSITIONS: 'olo_live_positions',
  OLO_SHOT_RESULT: 'olo_shot_result',
  MONOPOLY_STATE_UPDATED: 'monopoly_state_updated',
  CONQUEST_STATE_UPDATED: 'conquest_state_updated',
  CONQUEST_ATTACK_RESULT: 'conquest_attack_result',
} as const;
